services:
  receiver:
    container_name: receiver
    build: ./receiver
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./receiver:/app/
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW
      - NET_ADMIN
    networks:
      my_network:
        ipv4_address: 172.36.0.3
    command: python /app/receiver.py
  sender:
    container_name: sender
    build: ./sender
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./sender:/app/
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW
      - NET_ADMIN
    networks:
      my_network:
        ipv4_address: 172.36.0.4
    command: python /app/sender.py
networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.36.0.0/24