version: '3.8'

services:

  receiver:
    container_name: receiver
    build: ./receiver
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./receiver:/app/
    networks:
      my_network:
        ipv4_address: 172.36.0.3
    cap_add:
      - NET_BIND_SERVICE
    command: python /app/receiver.py

  sender:
    container_name: sender
    build: ./sender
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./sender:/app/
    networks:
      my_network:
        ipv4_address: 172.36.0.2
    command: python /app/sender.py

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.36.0.0/24
