version: '3.8'

services:
  sender:
    container_name: sender
    build: ./sender
    networks:
      my_network:
        ipv4_address: 172.36.0.2
    command: python /app/sender.py

  receiver:
    container_name: receiver
    build: ./receiver
    networks:
      my_network:
        ipv4_address: 172.36.0.3
    command: python /app/receiver.py

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.36.0.0/16
